Models/Link.cs
namespace webdev.Models
{
    public class Link
    {
        public int Id { get;set; }
        public string Long { get; set; }
        public string Short { get; set; }
    }
}

Controllers/LinkController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using webdev.Interfaces;
using webdev.Models;

namespace webdev.Controllers
{
    public class LinkController : Controller
    {
        private ILinksRepository _linksRepository;
        
        public LinkController(ILinksRepository linksRepository)
        {
            _linksRepository = linksRepository;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var links = _linksRepository.GetLinks();
            return View(links);
        }

        [HttpPost]
        public IActionResult Create(Link link)
        {
            _linksRepository.AddLink(link);
            return Redirect("Index");
        }

        [HttpGet]
        public IActionResult Delete(Link link)
        {
            _linksRepository.Delete(link);
            return Redirect("Index");
        }

        [HttpGet]
        public IActionResult DeleteAll()
        {
            _linksRepository.DeleteAll();
            return Redirect("Index");
        }
    }
}

Views/Link/Index.cshtml
@model List<webdev.Models.Link>
<div>
    @using (Html.BeginForm("Create", "Link", FormMethod.Post))
    {
        <input type="text" name="Long" placeholder="Full Link"/> <br/>
        <button type="submit">Add</button>
    }
</div>  
<div>
    <table>
        @foreach(var item in Model) {
            <tr>
                <td><strong>@Html.DisplayNameFor(model => item.Long):</strong></td>
                <td>@Html.DisplayFor(model => item.Long),</td>
                <td><strong>@Html.DisplayNameFor(model => item.Short):</strong></td>
                <td>@Html.DisplayFor(model => item.Short)</td>
                <td>@Html.ActionLink("Delete", "Delete", "Link", item)</td>
            </tr>
        }
    </table>
    @if(Model.Count>0)
    {
      <div>@Html.ActionLink("DeleteAll", "DeleteAll")</div>
    }
</div>